DROP TABLE IF EXISTS `books`;
CREATE TABLE books (id INT UNSIGNED NOT NULL AUTO_INCREMENT,   PRIMARY KEY (id),     title VARCHAR(50) NOT NULL,     author VARCHAR(50) NOT NULL,     status VARCHAR(30)NOT NULL );
